name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps: 
      - name: echo a string
        run: eccho "HelloWorld"
      - name: multiline script
        run: | 
          node -v
          npm -v