name: shell commands

on: 
  push:
    branches:
      - master
      - 'feature/*'  # will match feature/featA , feature/featB but will not match feature/featA/A
      - 'feature/**' # will match feature/featA , feature/featB will also match feature/featA/A
      - '!feature/featC'
    tags:
      - v1.*
    paths:
      - '**.js'
      - '!docs/**'
    # branches-ignore:
    #   - "development"

  # schedule:
  #   - cron: "*/5 * * * *"

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps: 
      - name: echo a string
        run: echo "HelloWorld"
      - name: multiline script
        run: | 
          node -v
          npm -v
      - name: Python script
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-cmd:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Directory powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash